default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: food_recipe_dev
  username: postgres
  password: Perento16
  host: localhost

test:
  <<: *default
  database: food_recipe_test
  username: postgres
  password: Perento16
  host: localhost

production:
  <<: *default
  database: food_recipe_prod
  username: postgres
  password: Perento16
  host: localhost
